### ISSUE TITLE
Code unrunnable on Linux/Unix

### ISSUE THREAD

**Issue by sadmansk** [Controls-UWNRG/minotaur#3]
And potentially on Windows as well if the computer is not connected to the serial port. This is the error output:

```
Traceback (most recent call last):
  File "main.py", line 679, in <module>
    app = MainWindow()
  File "main.py", line 368, in __init__
    self.__initialize_com_port()
  File "main.py", line 441, in __initialize_com_port
    facade.set_com_port(available_com_ports[0][0])
  File "/home/sadman/repos/minotaur/UWNRG_CURRENT/facade.py", line 109, in set_com_port
    _movement_controller.initialize_actuators(com_port)
  File "/home/sadman/repos/minotaur/UWNRG_CURRENT/movement/controller.py", line 106, in initialize_actuators
    self.__actuators = actuators.Actuators(com_port)
  File "/home/sadman/repos/minotaur/UWNRG_CURRENT/movement/actuators.py", line 1268, in __init__
    self.__ser = serial.Serial(com_port)
  File "/usr/lib/python2.7/site-packages/serial/serialutil.py", line 282, in __init__
    self.open()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 296, in open
    self._reconfigurePort()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 325, in _reconfigurePort
    raise SerialException("Could not configure port: %s" % msg)
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')
```

This makes the code impossible to test and debug when not using the main controls computer. It'd nice if someone else can test this as well.

**Comment by akeizer** [comment]
I have fix for this in the code. You have to add a command line argument to ask it to ignore the port. Its something like no ports. Check the code where it reads in the command line or sets up the ports, you should be able to see the argument there. I forget if I added it to the old wiki or not. 

At least I'm pretty sure this is the same issue.

**Comment by sadmansk** [comment]
Got it, thanks @AKeizer! Adding this to the readme.
